#!/usr/bin/env node
var fs = require("fs");
var uglify = require("uglify-js");
var stripper = require("./guard-stripper");

var minify = function (code) {
    var u = uglify.uglify;
    return u.gen_code(u.ast_squeeze(u.ast_mangle(uglify.parser.parse(code))));
};

var zeroPad = function (num) {
    return num < 10 ? "0" + num : num;
};

var addLicense = function (code) {
    var license = fs.readFileSync("LICENSE", "utf8");
    var version = JSON.parse(fs.readFileSync("package.json", "utf8")).version;
    var date = new Date();
    return "/**\n * Cull.JS " + version + ", " + date.getFullYear() + "-" +
        zeroPad(date.getMonth() + 1) + "-" + zeroPad(date.getDate()) + "\n * " +
        license.split("\n").join("\n * ") + "\n */\n" + code;
};

var opt = function (short, long) {
    for (var i = 2, l = process.argv.length; i < l; ++i) {
        if (new RegExp(short + "|" + long).test(process.argv[i])) {
            return true;
        }
    }
    return false;
};

if (opt("-h", "--help")) {
    console.log("Produce the cull.js distribution");
    console.log("Usage:");
    console.log("    script/build [opt]");
    console.log("        -m --minify     Produce minified distribution");
    console.log("        -n --no-license Skip the license header");
    console.log("        -s --no-guards  Remove the helpful error messages");
    console.log("        -h --help       Show this message");
    process.exit(1);
}

try {
    fs.mkdirSync("dist");
} catch (e) {}

var cull = fs.readFileSync("lib/cull.js", "utf8");
var willMinify = opt("-m", "--minify");

if (opt("-s", "--no-guards")) {
    cull = stripper.stripGuardDecls(stripper.stripGuards(cull));
}

if (willMinify) {
    cull = minify(cull);
}

if (!opt("-n", "--no-license")) {
    cull = addLicense(cull);
}

var target = willMinify ? "dist/cull.min.js" : "dist/cull.js";
fs.writeFileSync(target, cull, "utf8");
var size = (Math.floor((cull.length * 1000 / 1024)) / 1000);
var message = "Produced " + (willMinify ? "minified " : "");
console.log(message + target + " (~" + size + "kB)");
